Health:
    prefix: /api/health
    resource: ../src/Health/Infrastructure/Api/routes.yaml
    trailing_slash_on_root: false
BookStore:
    prefix: /api/books
    resource: ../src/BookStore/Infrastructure/Api/routes.yaml
    trailing_slash_on_root: false
ApiLogin:
    path: /api/login
    methods: [POST]
Users:
    prefix: /api/users
    resource: ../src/Template/User/Infrastructure/Api/routes.yaml
    trailing_slash_on_root: false
WorkEntries:
    prefix: /api/work-entries
    resource: ../src/Template/WorkEntry/Infrastructure/Api/routes.yaml
    trailing_slash_on_root: false
TimeTracking:
    prefix: /api/work-entries
    resource: ../src/Template/TimeTracking/Infrastructure/Api/routes.yaml
    trailing_slash_on_root: false
