controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_heath_check:
    path:       /api/healthcheck
    controller: App\Controller\HealthcheckController
    methods:    GET

api_command_check:
    path: /api/commands
    controller: App\Controller\CommandHandlerController
    methods: POST
